### ISSUE TITLE
incompatible with Hawthorn

### ISSUE THREAD

**Issue by thraxil** [appsembler/xblock-launchcontainer#26]
`setup.py` specifies `XBlock<0.5`, which effectively restricts us to 0.4.14. Hawthorn requires XBlock==1.2.1 and we get import errors when trying to use an older version like 0.4.14.

Whatever issue is keeping us at `<0.5` will need to be fixed and that restriction relaxed for this to be usable on Hawthorn.

**Comment by briandant** [comment]
Yes, good call, @thraxil. This fix is planned for the current sprint. https://trello.com/c/bIH8f800/1908-8-ensure-the-launchcontainer-xblock-is-compatible-with-hawthorn. We need to support Dogwood --> Hawthorne, which could get thorny. I presume you've made this work with Hawthorne? (I haven't installed devstack yet.)

**Comment by thraxil** [comment]
We need a tagged release of 2.1.12 so we can deploy it on Hawthorn.

**Comment by OmarIthawi** [comment]
That's been fixed. Thanks!
