### ISSUE TITLE
Add option for "contact administrator" text

### ISSUE THREAD

**Issue by dfoster67** [appsembler/xblock-launchcontainer#29]
Can we set a parameter for the contact administrator text that is shown in the containerlauncher.js code?  It would take setting a parameter, and adding a field to the editor.  I don't have the sdk to test it, but would be glad to help as needed.

**Comment by dfoster67** [comment]
@bezidejni - I see you just accepted a PR that describes this editable text and an email link.  When would this be pushed into production for our OpenEdx site?

**Comment by bezidejni** [comment]
@dfoster67 The message itself isn't editable, but the email address of the support person is. It shows a message "Lab taking a long time to load? Try contacting contact@person.com" after 2 mins and the lab hasn't launched yet. To be honest, I'm not sure what the procedure is for getting this to your edX site, @bryanlandia will probably know more.

**Comment by bryanlandia** [comment]
@dfoster67 @bezidejni We are tracking deployment on Trello here https://trello.com/c/H7REhTOC/560-isc-deploy-the-newest-version-of-the-container-launcher-xblock-on-edx-staging

**Comment by bryanlandia** [comment]
No longer relevant
